// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp21TiQ0X3mge0iSqg36gOzhsgICZftLo',
    appId: '1:1022881448278:web:daa93c58008a76874556f7',
    messagingSenderId: '1022881448278',
    projectId: 'sparktalk-reddit',
    authDomain: 'sparktalk-reddit.firebaseapp.com',
    storageBucket: 'sparktalk-reddit.firebasestorage.app',
    measurementId: 'G-VVGC48J1GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqf63Ls3NOH7UFUv2DsMnpMY6jQcUZwyY',
    appId: '1:1022881448278:android:58e5cd6d22c9e4084556f7',
    messagingSenderId: '1022881448278',
    projectId: 'sparktalk-reddit',
    storageBucket: 'sparktalk-reddit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtFLT-xiPjO9tfPNNIFuJIZN-fl7jigmw',
    appId: '1:1022881448278:ios:14ba746c1dcda05f4556f7',
    messagingSenderId: '1022881448278',
    projectId: 'sparktalk-reddit',
    storageBucket: 'sparktalk-reddit.firebasestorage.app',
    iosBundleId: 'com.example.sparkTalkReddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtFLT-xiPjO9tfPNNIFuJIZN-fl7jigmw',
    appId: '1:1022881448278:ios:14ba746c1dcda05f4556f7',
    messagingSenderId: '1022881448278',
    projectId: 'sparktalk-reddit',
    storageBucket: 'sparktalk-reddit.firebasestorage.app',
    iosBundleId: 'com.example.sparkTalkReddit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp21TiQ0X3mge0iSqg36gOzhsgICZftLo',
    appId: '1:1022881448278:web:0e75eeaccb2e19a94556f7',
    messagingSenderId: '1022881448278',
    projectId: 'sparktalk-reddit',
    authDomain: 'sparktalk-reddit.firebaseapp.com',
    storageBucket: 'sparktalk-reddit.firebasestorage.app',
    measurementId: 'G-8R7GRR2TND',
  );
}
